import { useCallback, useEffect, useRef, useState, type JSX } from "react";
import { AnimatePresence, motion } from "motion/react";
import { BulbAvatar, type BulbState } from "./BulbAvatar";
import { Controls } from "./Controls";
import { MargoLogo } from "./MargoLogo";
import { ReflectionView } from "./ReflectionView";
import { PracticeView } from "./PracticeView";
import { useScribe } from "./useScribe";
import { useReflection } from "./useReflection";
import { useFollowup } from "./useFollowup";
import { usePractice } from "./usePractice";
import { Onboarding } from "./Onboarding";
import { useOnboarding } from "./useOnboarding";
import { useEntries, countWords } from "./useEntries";
import { HistoryView } from "./HistoryView";
import { EntryDetailView } from "./EntryDetailView";
import { type NavTab } from "./BottomNav";

// The journaling entry always opens with this fixed prompt. The remaining
// prompts are generated live by the AI from the conversation (see `useFollowup`).
// The conversation is endless — it only ends when the user taps finish.
const OPENING_QUESTION = "How was your day?";

type Phase =
  | "onboarding"
  | "entry"
  | "loading"
  | "reflection"
  | "practice"
  | "history"
  | "historyDetail";

// Minimum time the white "preparing" loading screen shows, so the transition
// into the reflection feels calm even if generation resolves quickly.
const LOADING_MS = 1900;

export const Frame = (): JSX.Element => {
  // Persisted onboarding state (name + completion flag in localStorage).
  const { name, onboardingComplete, setName, completeOnboarding } =
    useOnboarding();

  // Which screen we're on. New users land in the voice-first onboarding;
  // returning users (onboardingComplete) skip straight to the journaling app.
  const [phase, setPhase] = useState<Phase>(
    onboardingComplete ? "entry" : "onboarding",
  );

  // --- Entry conversation state machine -------------------------------
  const [bulbState, setBulbState] = useState<BulbState>("idle");
  const [currentQuestion, setCurrentQuestion] = useState(OPENING_QUESTION);
  const [personTranscript, setPersonTranscript] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  // True while the user has switched to keyboard input for the current turn.
  const [isTyping, setIsTyping] = useState(false);
  const [burstKey, setBurstKey] = useState(0);
  // True once the user has started talking at least once this session. Used to
  // show the one-time "Tap to speak" hint only on the very first question and
  // never again afterward.
  const [hasEverSpoken, setHasEverSpoken] = useState(false);
  // How many prompts the user has answered so far (opener counts as the first
  // prompt). Used as the follow-up step index when generating questions.
  const promptCount = useRef(0);

  // Reflection screen: true while the AI "reads" the summary (drives the wave).
  const [reflectionSpeaking, setReflectionSpeaking] = useState(false);

  // Past entries (persisted) + which one is open in the detail view.
  const { entries, addEntry } = useEntries();
  const [selectedEntryId, setSelectedEntryId] = useState<string | null>(null);
  // When the current session started, to compute its duration on finish.
  const entryStartedAt = useRef<number>(0);

  const started = bulbState !== "idle";
  const aiSpeaking = bulbState === "aiSpeaking";
  const personSpeaking = bulbState === "personSpeaking";


  // ===================================================================
  // PLUG IN REAL AI HERE
  //   • aiSay(text)            → call when the AI produces a new message.
  //   • listen()               → call when you start capturing the user.
  //   • setPersonTranscript(s) → feed live speech-to-text results into this.
  //
  // Speech-to-text is wired to ElevenLabs Scribe v2 Realtime via `useScribe`
  // (driven by `isRecording`), and the reflection is generated by an LLM via
  // `useReflection` on finish. AI follow-up questions are still mocked.
  // ===================================================================
  const {
    start: startScribe,
    stop: stopScribe,
    error: scribeError,
  } = useScribe(setPersonTranscript);

  // Accumulated journal: each Q&A turn the user spoke this session. Fed to the
  // reflection generator when the entry finishes.
  const transcriptLog = useRef<string[]>([]);
  const { reflection, generate: generateReflection } = useReflection();
  const { next: generateFollowup } = useFollowup();
  // Tonight's personalized, therapy-grounded practice, generated from the same
  // transcript as the reflection (in parallel, during the loading screen).
  const { practice, generate: generatePractice } = usePractice();

  // Record a completed turn (the question the AI asked + what the user said).
  const recordTurn = useCallback((question: string, answer: string) => {
    const said = answer.trim();
    if (!said) return;
    transcriptLog.current.push(`Q: ${question}\nA: ${said}`);
  }, []);

  const aiSay = useCallback((question: string) => {
    setCurrentQuestion(question);
    setPersonTranscript("");
    setIsTyping(false);
    setBulbState("aiSpeaking");
  }, []);

  const listen = useCallback(() => {
    setBulbState("personSpeaking");
  }, []);
  // ===================================================================

  // Advance the conversation after the user finishes a turn: record it, then
  // ask the next AI-generated follow-up (built from the conversation so far).
  // The entry only wraps up when the user taps the finish button.
  const advanceConversation = useCallback(() => {
    recordTurn(currentQuestion, personTranscript);
    setIsRecording(false);

    // The conversation is endless: each "next" generates another AI follow-up.
    // The entry only ends when the user taps the finish (check mark) button.
    const step = promptCount.current - 1; // 0-based index of this follow-up
    promptCount.current += 1;

    // Show the thinking orb immediately, then swap in the generated question.
    setPersonTranscript("");
    setCurrentQuestion("");
    setIsTyping(false);
    setBulbState("aiSpeaking");

    void generateFollowup(transcriptLog.current.join("\n\n"), step, name).then(
      (question) => {
        aiSay(question);
      },
    );
  }, [
    aiSay,
    currentQuestion,
    generateFollowup,
    name,
    personTranscript,
    recordTurn,
  ]);

  const handleStartEntry = () => {
    promptCount.current = 1; // the opener is the first prompt
    transcriptLog.current = [];
    entryStartedAt.current = Date.now();
    setHasEverSpoken(false);
    setBurstKey((k) => k + 1);
    aiSay(OPENING_QUESTION);
  };

  const handleMicToggle = () => {
    if (isRecording) {
      // Pause recording but stay in this turn — the user can switch to the
      // keyboard, then tap the mic again to resume and keep talking. Advancing
      // to the next prompt / finishing is handled by the side buttons.
      setIsRecording(false);
    } else {
      // (Re)activate the mic. Any text already captured (spoken or typed) is
      // kept; new speech is appended to it via the scribe seed.
      setIsTyping(false);
      setIsRecording(true);
      setHasEverSpoken(true);
      listen();
    }
  };

  const handleToggleKeyboard = () => {
    if (isTyping) {
      // Leaving keyboard mode — keep the typed text; the user can tap the mic
      // to resume speaking (it will append to what they typed).
      setIsTyping(false);
    } else {
      // Switching to keyboard pauses the mic so speech doesn't fight typing.
      // Enter the person-speaking turn so the textarea is shown even when the
      // user types first (before ever starting the mic on this prompt).
      setIsRecording(false);
      setIsTyping(true);
      setHasEverSpoken(true);
      listen();
    }
  };

  const handleNextPrompt = () => {
    advanceConversation();
  };

  // Finish entry → stop recording, capture the final turn, then run the
  // minimum loading time and reflection generation in parallel; advance to the
  // reflection only once both have settled.
  const handleFinishEntry = useCallback((alreadyRecorded = false) => {
    if (isRecording) setIsRecording(false);
    if (!alreadyRecorded && personTranscript)
      recordTurn(currentQuestion, personTranscript);
    setPhase("loading");

    // Capture session stats now (audio is never stored — only the transcript).
    const transcript = transcriptLog.current.join("\n\n");
    const durationMs = entryStartedAt.current
      ? Date.now() - entryStartedAt.current
      : 0;
    const wordCount = countWords(transcript);

    const minDelay = new Promise<void>((r) => setTimeout(r, LOADING_MS));
    const generation = generateReflection(transcript);
    // Generate tonight's practice from the same transcript, in parallel. It's
    // not on the critical path to the reflection screen — by the time the user
    // taps "Start daily practice" it's typically ready (falls back otherwise).
    if (transcript.trim()) void generatePractice(transcript, name);
    void Promise.all([minDelay, generation]).then(([, generated]) => {
      // Persist the finished session so it appears in the History tab.
      if (transcript.trim() && generated.summary) {
        addEntry({
          topic: generated.topic || "Journal entry",
          durationMs,
          wordCount,
          transcript,
          reflection: generated,
        });
      }
      setReflectionSpeaking(true);
      setPhase("reflection");
    });
  }, [
    addEntry,
    currentQuestion,
    generatePractice,
    generateReflection,
    isRecording,
    name,
    personTranscript,
    recordTurn,
  ]);

  // Reflection CTA → the practice experience (third step). The practice was
  // already generated in parallel during the loading screen (see
  // handleFinishEntry); here we just transition to it.
  const handleStartDailyPractice = () => {
    setReflectionSpeaking(false);
    setPhase("practice");
  };

  // Back to home → reset the whole flow to the idle entry screen.
  const handleBackHome = useCallback(() => {
    // TODO: connect to real navigation. For now, reset to the start.
    console.log("[nav] back to home");
    setIsRecording(false);
    setIsTyping(false);
    setHasEverSpoken(false);
    setReflectionSpeaking(false);
    setPersonTranscript("");
    transcriptLog.current = [];
    promptCount.current = 0;
    setBulbState("idle");
    setPhase("entry");
  }, []);

  // Tapping the logo goes home (the main entry screen) — but only if we
  // already have the user's name. Without a name we're still onboarding, so
  // there's nowhere to skip to and the tap is a no-op.
  const handleLogoClick = useCallback(() => {
    if (!name) return;
    handleBackHome();
  }, [name, handleBackHome]);

  // Bottom-nav tab selection between the journaling flow and the history list.
  const handleSelectTab = (tab: NavTab) => {
    if (tab === "journal") {
      setPhase("entry");
    } else {
      setSelectedEntryId(null);
      setPhase("history");
    }
  };

  const handleOpenEntry = (id: string) => {
    setSelectedEntryId(id);
    setPhase("historyDetail");
  };

  const selectedEntry =
    entries.find((entry) => entry.id === selectedEntryId) ?? null;

  // The bottom nav is shown only on the history tab now — the home/entry
  // screen uses a minimal bare history icon instead of the full tab bar.
  const navTab: NavTab | null = phase === "history" ? "history" : null;

  // Live speech-to-text via ElevenLabs Scribe. Start a streaming session when
  // recording begins and tear it down when it stops. `useScribe` feeds results
  // into `setPersonTranscript`. When resuming a turn (after a keyboard edit or
  // a pause) we seed Scribe with the existing transcript so new speech is
  // appended rather than overwriting what's already there.
  const transcriptRef = useRef("");
  useEffect(() => {
    transcriptRef.current = personTranscript;
  }, [personTranscript]);

  useEffect(() => {
    if (!isRecording) return;
    void startScribe(transcriptRef.current);
    return () => {
      stopScribe();
    };
  }, [isRecording, startScribe, stopScribe]);

  return (
    <main className="flex min-h-dvh w-full items-center justify-center overflow-auto bg-[#f3f3f3] p-4">
      <section className="relative flex h-[844px] w-[390px] shrink-0 flex-col overflow-hidden rounded-[44px] bg-white shadow-[0_20px_60px_rgba(0,0,0,0.12)]">
        <AnimatePresence mode="wait">
          {phase === "onboarding" ? (
            <Onboarding
              key="onboarding"
              onName={setName}
              onStartNoticing={() => {
                completeOnboarding();
                setPhase("entry");
              }}
              onSaveAndExit={() => {
                completeOnboarding();
                setPhase("entry");
              }}
              onSkipToHome={() => {
                completeOnboarding();
                handleBackHome();
              }}
            />
          ) : phase === "entry" ? (
            <motion.div
              key="entry"
              // Exit upward + shrink so it reads like the orb flowing up into
              // the voice bar on the next screen.
              exit={{ opacity: 0, y: -60, scale: 0.92 }}
              transition={{ duration: 0.5, ease: "easeInOut" }}
              className="relative flex h-full w-full flex-col items-center px-6 pt-[118px] pb-[40px]"
            >
              {/* Brand logo, anchored at the top of the entry screen. */}
              <MargoLogo
                onClick={handleLogoClick}
                className="absolute top-7 left-1/2 -translate-x-1/2"
              />

              {/* Title fades out and unmounts once the entry starts. */}
              <AnimatePresence>
                {!started && (
                  <motion.div
                    key="title"
                    initial={false}
                    exit={{ opacity: 0, y: -8 }}
                    transition={{ duration: 0.4, ease: "easeOut" }}
                    className="flex flex-col items-center gap-2"
                  >
                    <h1
                      id="activate-agent-title"
                      className="relative w-fit [font-family:'Inter',Helvetica] font-medium text-[#1c2b33] text-[30px] text-center tracking-[-0.5px] leading-[1.2] whitespace-nowrap pb-px"
                    >
                      {name ? "Welcome back, Sara" : "Activate Agent"}
                    </h1>
                    <p className="max-w-[280px] text-center [font-family:'Inter',Helvetica] font-normal text-[15px] leading-[21px] text-[#1c2b33]/50">
                      {name
                        ? "Ready to think out loud?"
                        : "Your space to think out loud."}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Bulb + AI question stack, vertically centered. */}
              <div className="flex w-full flex-1 flex-col items-center justify-center gap-9">
                <div className="relative flex flex-col items-center justify-center gap-7">
                  <div className="relative flex items-center justify-center">
                    <AnimatePresence>
                      {burstKey > 0 && (
                        <motion.span
                          key={burstKey}
                          aria-hidden="true"
                          className="absolute h-[232px] w-[232px] rounded-full bg-[linear-gradient(135deg,rgba(244,231,255,1)_0%,rgba(253,221,222,1)_100%)] blur-xl"
                          initial={{ opacity: 0.6, scale: 1 }}
                          animate={{ opacity: 0, scale: 1.7 }}
                          transition={{ duration: 0.7, ease: "easeOut" }}
                        />
                      )}
                    </AnimatePresence>

                    {/* Idle: the whole orb is the tap-to-begin affordance.
                        Once started, tapping the orb toggles the mic on/off —
                        identical to the mic button in the controls. */}
                    {!started ? (
                      <button
                        type="button"
                        onClick={handleStartEntry}
                        aria-label="Tap to begin"
                        className="all-[unset] box-border cursor-pointer rounded-full focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#1c2b33]"
                      >
                        <BulbAvatar state={bulbState} />
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={handleMicToggle}
                        aria-label={isRecording ? "Tap to pause" : "Tap to speak"}
                        aria-pressed={isRecording}
                        className="all-[unset] box-border cursor-pointer rounded-full focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#1c2b33]"
                      >
                        <BulbAvatar state={bulbState} />
                      </button>
                    )}
                  </div>

                  {/* "Tap to speak" hint under the orb. Shown on the intro
                      screen (tap to begin) and on the opening question until
                      the user first starts talking — then gone for the
                      session. */}
                  <AnimatePresence>
                    {(!started ||
                      (aiSpeaking &&
                        !hasEverSpoken &&
                        currentQuestion === OPENING_QUESTION)) && (
                      <motion.span
                        key="tap-to-speak"
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -6 }}
                        transition={{ duration: 0.4, ease: "easeOut" }}
                        className="pointer-events-none [font-family:'Inter',Helvetica] font-medium uppercase tracking-[1.5px] text-[12px] text-[#1c2b33]/40"
                      >
                        Tap to speak
                      </motion.span>
                    )}
                  </AnimatePresence>
                </div>

                <AnimatePresence mode="wait">
                  {(aiSpeaking || personSpeaking) && currentQuestion && (
                    <motion.p
                      key={currentQuestion}
                      initial={{ opacity: 0, y: 10, scale: 0.98 }}
                      animate={{
                        opacity: personSpeaking ? 0.55 : 1,
                        y: 0,
                        scale: personSpeaking ? 0.92 : 1,
                      }}
                      exit={{ opacity: 0, y: -10 }}
                      transition={{ duration: 0.5, ease: "easeOut" }}
                      className="max-w-[320px] px-2 text-center [font-family:'Inter',Helvetica] font-medium text-[#1c2b33] text-[24px] leading-[1.3] tracking-[-0.4px]"
                    >
                      {currentQuestion}
                    </motion.p>
                  )}
                </AnimatePresence>
              </div>

              {/* Bottom block: transcript + controls (started). */}
              <div className="flex w-full flex-col items-center">
                <AnimatePresence mode="wait">
                  {started && (
                    <motion.div
                      key="live"
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.5, ease: "easeOut" }}
                      className="flex w-full flex-col items-center gap-7"
                    >
                      <div className="flex min-h-[64px] w-full items-end justify-center px-2">
                        <AnimatePresence mode="wait">
                          {personSpeaking && !isTyping && (
                            <motion.div
                              key="transcript"
                              initial={{ opacity: 0, y: 10 }}
                              animate={{ opacity: 1, y: 0 }}
                              exit={{ opacity: 0, y: 8 }}
                              transition={{ duration: 0.35, ease: "easeOut" }}
                              className="flex w-full flex-col items-center gap-2"
                            >
                              <span className="[font-family:'Inter',Helvetica] font-medium uppercase tracking-[1.5px] text-[12px] text-[#1c2b33]/40">
                                Your turn
                              </span>
                              <p className="max-w-[300px] text-center [font-family:'Inter',Helvetica] font-normal text-[15px] leading-[22px] text-[#1c2b33]/55">
                                {personTranscript ||
                                  (isRecording ? "Listening…" : "Tap the mic or keyboard to begin")}
                              </p>
                              {scribeError && (
                                <p className="max-w-[300px] text-center [font-family:'Inter',Helvetica] font-normal text-[13px] leading-[18px] text-[#d4576a]">
                                  {scribeError}
                                </p>
                              )}
                            </motion.div>
                          )}
                          {personSpeaking && isTyping && (
                            <motion.div
                              key="typing"
                              initial={{ opacity: 0, y: 10 }}
                              animate={{ opacity: 1, y: 0 }}
                              exit={{ opacity: 0, y: 8 }}
                              transition={{ duration: 0.3, ease: "easeOut" }}
                              className="flex w-full flex-col items-center gap-2"
                            >
                              <span className="[font-family:'Inter',Helvetica] font-medium uppercase tracking-[1.5px] text-[12px] text-[#1c2b33]/40">
                                Your turn
                              </span>
                              <textarea
                                autoFocus
                                value={personTranscript}
                                onChange={(e) => setPersonTranscript(e.target.value)}
                                placeholder="Type to add to your entry…"
                                rows={2}
                                className="w-full max-w-[300px] resize-none rounded-2xl border border-[rgba(244,231,255,0.9)] bg-white/70 px-4 py-3 text-center [font-family:'Inter',Helvetica] text-[15px] font-normal leading-[22px] text-[#1c2b33] shadow-[0_6px_16px_rgba(28,43,51,0.06)] placeholder:text-[#1c2b33]/35 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#b6a0e0]"
                              />
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>

                      <Controls
                        isRecording={isRecording}
                        isTyping={isTyping}
                        onMicToggle={handleMicToggle}
                        onToggleKeyboard={handleToggleKeyboard}
                        onFinish={() => handleFinishEntry()}
                        onNext={handleNextPrompt}
                      />
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              {/* Minimal history affordance: a bare icon in the bottom-right
                  corner (replaces the bottom tab bar on the home screen). */}
              <AnimatePresence>
                {!started && (
                  <motion.button
                    key="history-fab"
                    type="button"
                    onClick={() => {
                      setSelectedEntryId(null);
                      setPhase("history");
                    }}
                    aria-label="History"
                    initial={false}
                    exit={{ opacity: 0 }}
                    whileTap={{ scale: 0.9 }}
                    className="all-[unset] absolute right-7 bottom-8 box-border flex h-11 w-11 cursor-pointer items-center justify-center rounded-full text-[#1c2b33]/40 transition-colors hover:text-[#1c2b33]/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1c2b33]"
                  >
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      aria-hidden="true"
                      stroke="currentColor"
                      strokeWidth={1.7}
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M3 12a9 9 0 1 0 3-6.7" />
                      <path d="M3 4v4h4" />
                      <path d="M12 8v4l2.5 2.5" />
                    </svg>
                  </motion.button>
                )}
              </AnimatePresence>
            </motion.div>
          ) : phase === "loading" ? (
            // White "preparing" loading screen with an animated icon.
            <motion.div
              key="loading"
              role="status"
              aria-live="polite"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4, ease: "easeOut" }}
              className="flex h-full w-full flex-col items-center justify-center gap-6 bg-white px-8 text-center"
            >
              {/* Animated loading icon — a soft pastel spinner. */}
              <motion.span
                aria-hidden="true"
                className="h-10 w-10 rounded-full border-[3px] border-[#ece3ff] border-t-[#c7a6f5]"
                animate={{ rotate: 360 }}
                transition={{ duration: 0.9, repeat: Infinity, ease: "linear" }}
              />
              <div className="flex flex-col gap-2">
                <p className="[font-family:'Inter',Helvetica] text-[24px] font-medium tracking-[-0.4px] text-[#1c2b33]">
                  Wrapping up your entry…
                </p>
                <p className="[font-family:'Inter',Helvetica] text-[15px] font-normal text-[#1c2b33]/55">
                  Preparing your summary &amp; practice.
                </p>
              </div>
            </motion.div>
          ) : phase === "reflection" ? (
            <ReflectionView
              key="reflection"
              summary={reflection.summary}
              patterns={reflection.patterns}
              nextSteps={reflection.nextSteps}
              aiSpeaking={reflectionSpeaking}
              onSummaryComplete={() => setReflectionSpeaking(false)}
              onStartDailyPractice={handleStartDailyPractice}
            />
          ) : phase === "practice" ? (
            <PracticeView
              key="practice"
              practice={practice}
              onBackHome={handleBackHome}
            />
          ) : phase === "history" ? (
            <HistoryView
              key="history"
              entries={entries}
              onOpenEntry={handleOpenEntry}
            />
          ) : selectedEntry ? (
            <EntryDetailView
              key="history-detail"
              entry={selectedEntry}
              onBack={() => {
                setSelectedEntryId(null);
                setPhase("history");
              }}
            />
          ) : (
            // Fallback: a selected entry went missing — return to the list.
            <HistoryView
              key="history-fallback"
              entries={entries}
              onOpenEntry={handleOpenEntry}
            />
          )}
        </AnimatePresence>

        {/* Sticky Home pill on the history tab — gradient matches the orb. */}
        <AnimatePresence>
          {navTab && (
            <motion.div
              key="bottom-nav"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 16 }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="pointer-events-none absolute inset-x-0 bottom-0 z-20 flex justify-center px-6 pb-[max(1.25rem,env(safe-area-inset-bottom))]"
            >
              <motion.button
                type="button"
                onClick={() => handleSelectTab("journal")}
                aria-label="Home"
                whileTap={{ scale: 0.96 }}
                className="all-[unset] pointer-events-auto box-border flex h-12 cursor-pointer items-center gap-2 rounded-full px-6 text-white shadow-[0_14px_34px_rgba(199,166,245,0.45)] transition-transform hover:scale-[1.03] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#c7a6f5]"
                style={{
                  background:
                    "linear-gradient(90deg, #c7a6f5 0%, #ec9fc4 52%, #f7b59a 100%)",
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  aria-hidden="true"
                  stroke="currentColor"
                  strokeWidth={1.9}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M3 10.5 12 3l9 7.5" />
                  <path d="M5 9.5V20a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V9.5" />
                </svg>
                <span className="[font-family:'Inter',Helvetica] text-[15px] font-semibold tracking-[-0.2px]">
                  Home
                </span>
              </motion.button>
            </motion.div>
          )}
        </AnimatePresence>
      </section>
    </main>
  );
};
