import { useCallback, useRef, useState } from "react";

/* ============================================================================
 * useInsights — the cross-entry "period reflection" shown at the top of the
 * Insights screen. Unlike the per-entry reflection, this looks ACROSS many
 * entries in the selected time range and names the through-line.
 *
 * Generated by the same `/api/reflection` proxy in `insights` mode. Falls back
 * to a gentle generic narrative when no LLM key is configured or the request
 * fails, so the screen always reads as finished.
 * ==========================================================================*/
export interface Insights {
  /** One warm sentence naming the through-line of the period. */
  headline: string;
  /** 1-2 sentences: the recurring pattern across entries. */
  throughLine: string;
  /** What's changing/emerging across entries — empty if too little to compare. */
  shift: string;
  /** One pointed, forward-looking question for the period ahead. */
  question: string;
}

const INSIGHTS_ENDPOINT = "/api/reflection";

/** Generic fallback so the screen still reads as finished without a key. */
export const MOCK_INSIGHTS: Insights = {
  headline: "You keep showing up here — that already says something.",
  throughLine:
    "Across these entries you circle back to the same handful of feelings. The details change; the weight underneath them doesn't.",
  shift: "",
  question: "What's one thing you'd like to feel differently about next time?",
};

interface UseInsightsResult {
  insights: Insights;
  generating: boolean;
  usedFallback: boolean;
  /**
   * Generate the period reflection from a digest of the in-range entries via
   * the `/api/reflection` proxy in `insights` mode. Falls back to
   * `MOCK_INSIGHTS` if the digest is empty, the key is missing, or the request
   * fails. Guarded by a request id so a slower earlier range can't overwrite a
   * newer one when the user switches ranges quickly.
   */
  generate: (digest: string, name?: string) => Promise<void>;
}

export function useInsights(): UseInsightsResult {
  const [insights, setInsights] = useState<Insights>(MOCK_INSIGHTS);
  const [generating, setGenerating] = useState(false);
  const [usedFallback, setUsedFallback] = useState(true);
  const requestId = useRef(0);

  const generate = useCallback(async (digest: string, name?: string) => {
    const id = ++requestId.current;
    setGenerating(true);

    const fall = () => {
      if (id !== requestId.current) return;
      setInsights(MOCK_INSIGHTS);
      setUsedFallback(true);
    };

    if (!digest.trim()) {
      fall();
      setGenerating(false);
      return;
    }

    try {
      const res = await fetch(INSIGHTS_ENDPOINT, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ transcript: digest, mode: "insights", name }),
      });

      if (!res.ok) {
        fall();
        return;
      }

      const data = (await res.json()) as Insights;
      if (id !== requestId.current) return; // superseded
      setInsights(data);
      setUsedFallback(false);
    } catch {
      fall();
    } finally {
      if (id === requestId.current) setGenerating(false);
    }
  }, []);

  return { insights, generating, usedFallback, generate };
}
