import { useCallback, useRef, useState } from "react";

/* ============================================================================
 * useInsights — the cross-entry "period reflection" shown at the top of the
 * Insights screen. Unlike the per-entry reflection, this looks ACROSS many
 * entries in the selected time range and names the through-line.
 *
 * Generated by the same `/api/reflection` proxy in `insights` mode. Falls back
 * to a gentle generic narrative when no LLM key is configured or the request
 * fails, so the screen always reads as finished.
 * ==========================================================================*/
export interface Insights {
  /** One warm sentence naming the through-line of the period. */
  headline: string;
  /** 1-2 sentences: the recurring pattern across entries. */
  throughLine: string;
  /** What's changing/emerging across entries — empty if too little to compare. */
  shift: string;
  /** One pointed, forward-looking question for the period ahead. */
  question: string;
}

const INSIGHTS_ENDPOINT = "/api/reflection";

/** Generic fallback so the screen still reads as finished without a key. */
export const MOCK_INSIGHTS: Insights = {
  headline: "You keep showing up here — that already says something.",
  throughLine:
    "Across these entries you circle back to the same handful of feelings. The details change; the weight underneath them doesn't.",
  shift: "",
  question: "What's one thing you'd like to feel differently about next time?",
};

interface UseInsightsResult {
  insights: Insights;
  generating: boolean;
  usedFallback: boolean;
  /**
   * The `key` (e.g. the selected range) the current `insights` belongs to, or
   * `null` before anything has resolved. Lets the view tell a *fresh* result
   * for the current range apart from a *stale* one left over from a previous
   * range, so it can show a loading skeleton instead of the old narrative.
   */
  resultKey: string | null;
  /**
   * Generate the period reflection from a digest of the in-range entries via
   * the `/api/reflection` proxy in `insights` mode. Falls back to
   * `MOCK_INSIGHTS` if the digest is empty, the key is missing, or the request
   * fails. Guarded by a request id so a slower earlier range can't overwrite a
   * newer one when the user switches ranges quickly. `key` tags the result
   * (pass the range) so the view knows which selection it corresponds to.
   */
  generate: (digest: string, name?: string, key?: string) => Promise<void>;
}

export function useInsights(): UseInsightsResult {
  const [insights, setInsights] = useState<Insights>(MOCK_INSIGHTS);
  const [generating, setGenerating] = useState(false);
  const [usedFallback, setUsedFallback] = useState(true);
  const [resultKey, setResultKey] = useState<string | null>(null);
  const requestId = useRef(0);

  const generate = useCallback(
    async (digest: string, name?: string, key?: string) => {
      const id = ++requestId.current;
      const tag = key ?? null;
      setGenerating(true);

      const settle = (next: Insights, fallback: boolean) => {
        if (id !== requestId.current) return;
        setInsights(next);
        setUsedFallback(fallback);
        setResultKey(tag);
      };

      if (!digest.trim()) {
        settle(MOCK_INSIGHTS, true);
        if (id === requestId.current) setGenerating(false);
        return;
      }

      try {
        const res = await fetch(INSIGHTS_ENDPOINT, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ transcript: digest, mode: "insights", name }),
        });

        if (!res.ok) {
          settle(MOCK_INSIGHTS, true);
          return;
        }

        const data = (await res.json()) as Insights;
        settle(data, false); // no-op if superseded
      } catch {
        settle(MOCK_INSIGHTS, true);
      } finally {
        if (id === requestId.current) setGenerating(false);
      }
    },
    [],
  );

  return { insights, generating, usedFallback, resultKey, generate };
}
